### ISSUE TITLE
Error when running for a long time 

### ISSUE THREAD

**Issue by MinerBigWhale** [AaltoAsia/O-MI#16]
Hello guys,

When we leave our OMInode running for a long time this error occurs and the node do not return any usable data. 

Any request return `<error>Internal Server Error</error>`

The ODF explorer is working properly but no request works.

Here are the errors into the server's logs.
```
2018-10-24 14:27:18,337 ERROR database.DBHandler - Error when trying to update hierarchy.
akka.pattern.AskTimeoutException: Recipient[Actor[akka://on-core/user/$b#1798215470]] had already been terminated. Sender[Actor[akka://on-core/user/database-handler#1588559709]] sent the message of type "database.journal.Models$UnionCommand".
   at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:291) ~[com.typesafe.akka.akka-actor_2.12-2.5.12.jar:2.5.12]
   at akka.pattern.AskableActorRef$.$qmark$extension1(AskSupport.scala:283) ~[com.typesafe.akka.akka-actor_2.12-2.5.12.jar:2.5.12]
   at database.DBWriteHandler.$anonfun$handleWrite$25(DBWriteHandler.scala:268) ~[o-mi-backend.o-mi-backend-1.0.2.jar:1.0.2]
   at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303) ~[org.scala-lang.scala-library-2.12.6.jar:na]
   at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37) ~[org.scala-lang.scala-library-2.12.6.jar:na]
   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) ~[org.scala-lang.scala-library-2.12.6.jar:na]
   at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[na:1.8.0_131]
   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_131]
   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_131]
   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_131]
   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_131]
2018-10-24 14:27:18,337 ERROR database.DBHandler - Error while handling write.
akka.pattern.AskTimeoutException: Recipient[Actor[akka://on-core/user/$b#1798215470]] had already been terminated. Sender[Actor[akka://on-core/user/database-handler#1588559709]] sent the message of type "database.journal.Models$UnionCommand".
   at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:291) ~[com.typesafe.akka.akka-actor_2.12-2.5.12.jar:2.5.12]
   at akka.pattern.AskableActorRef$.$qmark$extension1(AskSupport.scala:283) ~[com.typesafe.akka.akka-actor_2.12-2.5.12.jar:2.5.12]
   at database.DBWriteHandler.$anonfun$handleWrite$25(DBWriteHandler.scala:268) ~[o-mi-backend.o-mi-backend-1.0.2.jar:1.0.2]
   at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303) ~[org.scala-lang.scala-library-2.12.6.jar:na]
   at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37) ~[org.scala-lang.scala-library-2.12.6.jar:na]
   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) ~[org.scala-lang.scala-library-2.12.6.jar:na]
   at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[na:1.8.0_131]
   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_131]
   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_131]
   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_131]
   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_131]
2018-10-24 14:27:18,344 WARN  agents.JavaWaterbusBoatAgent - Something went wrong when JavaWaterbusBoatAgent wrote, InternalError(Some(Recipient[Actor[akka://on-core/user/$b#1798215470]] had already been terminated. Sender[Actor[akka://on-core/user/database-handler#1588559709]] sent the message of type “database.journal.Models$UnionCommand".))
akka.pattern.AskTimeoutException: Recipient[Actor[akka://on-core/user/$b#1798215470]] had already been terminated. Sender[Actor[akka://on-core/user/database-handler#1588559709]] sent the message of type "database.journal.Models$UnionCommand".
   at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:291)
   at akka.pattern.AskableActorRef$.$qmark$extension1(AskSupport.scala:283)
   at database.DBWriteHandler.$anonfun$handleWrite$25(DBWriteHandler.scala:268)
   at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
   at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
   at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Note that we use a Java Agent to provide some data (JavaWaterbusBoatAgent and JavaWaterbusStopAgent)

After a restart of the node, every things works once again till the next DBHandler Error (could be weeks after)

I put a watchdog that wait for that error to restart the service but that's only a workaround, not a real solution.

Regards,

**Comment by TK009** [comment]
This was due to memory leak in O-MI parser. It is fixed in [v1.0.6](https://github.com/AaltoAsia/O-MI/releases/tag/1.0.6)

**Comment by MinerBigWhale** [comment]
Please re-open, the problème still appear i v1.0.8 after 26Days running.

```
akka.pattern.AskTimeoutException: Recipient[Actor[akka://on-core/user/$b#818624683]] had already been terminated. Sender[Actor[akka://on-core/user/database-handler#-119259258]] sent the message of type "database.journal.Models$UnionCommand".
        at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:291)
        at akka.pattern.AskableActorRef$.$qmark$extension1(AskSupport.scala:283)
        at database.DBWriteHandler.$anonfun$handleWrite$25(DBWriteHandler.scala:268)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by TK009** [comment]
This Exception tells that the component that stores O-DF hierarchy (without the values), have crashed.

Could you try to answer these questions:

1. What is the first error in logs? (if different)
2. Is there RAM and disk space available?
3. Is there any way we could reproduce this error?

I inspected the related code sections and it only tries to merge the new O-DF to the old. One thing that can throw an error is that an InfoItem is written on top of existing Object or the other way around.
